const ADD_ALBUM_TO_BOX = 'ADD_ALBUM_TO_BOX';
const REMOVE_ALBUM_FROM_BOX = 'REMOVE_ALBUM_FROM_BOX';
const SET_PALETTE = ' SET_PALETTE';

export { ADD_ALBUM_TO_BOX, REMOVE_ALBUM_FROM_BOX, SET_PALETTE };
