const SET_PLAYING_STATE = 'SET_PLAYING_STATE';
const SET_PLAYLIST = 'SET_PLAYLIST';
const SET_DEFAULT_LIST = 'SET_DEFAULT_LIST';
const SET_PLAY_MODE = 'SET_PLAY_MODE';
const SET_CURRENT_IDX = 'SET_CURRENT_IDX';
const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
const PLAY_NOW = 'PLAY_NOW';

export {
	PLAY_NOW,
	SET_PLAYING_STATE,
	SET_PLAYLIST,
	SET_DEFAULT_LIST,
	SET_PLAY_MODE,
	SET_CURRENT_IDX,
	SET_CURRENT_SONG
};
