const GET_NEW_ALBUMS_LIST = 'GET_NEW_ALBUMS_LIST';
const SEARCH_ALBUMS = 'SEARCH_ALBUMS';
const ENTER_LOADING = 'ENTER_LOADING';
const SEARCH_LOADING = 'SEARCH_LOADING';
const GET_ALBUM_DETAIL = 'GET_ALBUM_DETAIL';
const DETAIL_LOADING = 'DETAIL_LOADING';
export { GET_NEW_ALBUMS_LIST, SEARCH_ALBUMS, ENTER_LOADING, SEARCH_LOADING, GET_ALBUM_DETAIL, DETAIL_LOADING };
